import type { Brief } from "@/types/brief"

export const sampleBriefs: Brief[] = [
  {
    id: "brief-1",
    name: "Website Design Brief",
    description: "Comprehensive brief for gathering website design requirements from clients",
    createdAt: "2025-05-15T10:30:00Z",
    updatedAt: "2025-05-20T14:45:00Z",
    questions: [
      {
        id: "q1",
        text: "What is the primary purpose of your website?",
        type: "textarea",
        required: true,
        description: "Describe the main goals and objectives of your website",
        placeholder: "e.g., Showcase products, generate leads, provide information...",
      },
      {
        id: "q2",
        text: "Who is your target audience?",
        type: "textarea",
        required: true,
        description: "Describe the demographics, interests, and needs of your ideal visitors",
      },
      {
        id: "q3",
        text: "Do you have an existing website?",
        type: "multiple-choice",
        required: true,
        options: [
          { id: "opt1", value: "Yes, and I want to redesign it" },
          { id: "opt2", value: "Yes, but I want to create a completely new one" },
          { id: "opt3", value: "No, this is my first website" },
        ],
      },
      {
        id: "q4",
        text: "What is your budget range for this project?",
        type: "dropdown",
        required: true,
        options: [
          { id: "budget1", value: "Less than $1,000" },
          { id: "budget2", value: "$1,000 - $5,000" },
          { id: "budget3", value: "$5,000 - $10,000" },
          { id: "budget4", value: "$10,000+" },
        ],
      },
      {
        id: "q5",
        text: "What is your desired launch date?",
        type: "date",
        required: true,
        description: "When would you like your website to go live?",
      },
      {
        id: "q6",
        text: "What features do you need on your website?",
        type: "checkbox",
        required: true,
        description: "Select all that apply",
        options: [
          { id: "feat1", value: "Contact Form" },
          { id: "feat2", value: "Blog/News Section" },
          { id: "feat3", value: "E-commerce/Online Store" },
          { id: "feat4", value: "Portfolio/Gallery" },
          { id: "feat5", value: "User Accounts/Login" },
          { id: "feat6", value: "Newsletter Signup" },
          { id: "feat7", value: "Social Media Integration" },
        ],
      },
    ],
  },
  {
    id: "brief-2",
    name: "Logo Design Brief",
    description: "Brief for collecting logo design requirements and brand information",
    createdAt: "2025-05-10T09:15:00Z",
    updatedAt: "2025-05-12T11:20:00Z",
    questions: [
      {
        id: "q1",
        text: "What is your company/brand name?",
        type: "text",
        required: true,
      },
      {
        id: "q2",
        text: "Describe your business and what you do",
        type: "textarea",
        required: true,
        description: "Include your products/services, industry, and target market",
      },
      {
        id: "q3",
        text: "What values or attributes do you want your logo to communicate?",
        type: "checkbox",
        required: true,
        description: "Select all that apply",
        options: [
          { id: "val1", value: "Professional" },
          { id: "val2", value: "Modern" },
          { id: "val3", value: "Traditional" },
          { id: "val4", value: "Playful" },
          { id: "val5", value: "Luxurious" },
          { id: "val6", value: "Minimalist" },
          { id: "val7", value: "Bold" },
          { id: "val8", value: "Eco-friendly" },
        ],
      },
      {
        id: "q4",
        text: "Do you have color preferences for your logo?",
        type: "textarea",
        required: false,
        description: "Specify any colors you'd like to use or avoid",
      },
      {
        id: "q5",
        text: "What style of logo are you looking for?",
        type: "multiple-choice",
        required: true,
        options: [
          { id: "style1", value: "Wordmark (text only)" },
          { id: "style2", value: "Lettermark (initials/monogram)" },
          { id: "style3", value: "Symbol/Icon with text" },
          { id: "style4", value: "Abstract mark" },
          { id: "style5", value: "Mascot" },
          { id: "style6", value: "Combination (multiple elements)" },
          { id: "style7", value: "Not sure - open to suggestions" },
        ],
      },
    ],
  },
  {
    id: "brief-3",
    name: "Marketing Campaign Brief",
    description: "Brief for planning and executing marketing campaigns",
    createdAt: "2025-05-05T14:20:00Z",
    updatedAt: "2025-05-08T16:30:00Z",
    questions: [
      {
        id: "q1",
        text: "What are the main objectives of this marketing campaign?",
        type: "textarea",
        required: true,
        description: "What specific goals are you trying to achieve?",
      },
      {
        id: "q2",
        text: "Who is your target audience for this campaign?",
        type: "textarea",
        required: true,
        description: "Be as specific as possible about demographics, interests, and behaviors",
      },
      {
        id: "q3",
        text: "What is your campaign budget?",
        type: "number",
        required: true,
        description: "Total budget in USD",
        min: 0,
      },
      {
        id: "q4",
        text: "What is the timeline for this campaign?",
        type: "multiple-choice",
        required: true,
        options: [
          { id: "time1", value: "Less than 1 month" },
          { id: "time2", value: "1-3 months" },
          { id: "time3", value: "3-6 months" },
          { id: "time4", value: "6+ months" },
        ],
      },
      {
        id: "q5",
        text: "Which marketing channels do you want to use?",
        type: "checkbox",
        required: true,
        description: "Select all that apply",
        options: [
          { id: "chan1", value: "Social Media" },
          { id: "chan2", value: "Email Marketing" },
          { id: "chan3", value: "Content Marketing" },
          { id: "chan4", value: "Paid Advertising" },
          { id: "chan5", value: "SEO" },
          { id: "chan6", value: "Events" },
          { id: "chan7", value: "Influencer Marketing" },
        ],
      },
    ],
  },
]

